export enum Genre {
  ROMANCE = 'ROMANCE',
  FANFIC = 'FANFIC',
  BUSINESS = 'BUSINESS',
  ADVENTURE = 'ADVENTURE',
  HORROR = 'HORROR',
  RELIGION = 'RELIGION',
  HISTORY = 'HISTORY',
  SELF_HELP = 'SELF_HELP',
  CLASSIC = 'CLASSIC',
  BIOGRAPHY = 'BIOGRAPHY',
}
